experiment:
  project_name: cbir_lumc_tissue
  annotation_file: /exports/path-pulmogroep-hpc/Jurre/SalvDataset/LUMC_cohort/annotations_key_diag_test.csv
  task: null
  mode: feature_extraction
  aggregation_level: slide
  report: true
  mixed_precision: true
  num_workers: 8
  split_technique: k-fold
  val_fraction: 0.1

slide_processing:
  backend: lazyslide
  save_tiles: false
  segmentation_method: otsu

datasets:
  - name: Salv-LUMC
    slide_path: /exports/path-pulmogroep-hpc/Jurre/SalvDataset/LUMC_cohort/slides
    used_for: testing

benchmark_parameters:
  tile_px:
    - 256
  tile_mpp:
    - 0.25
  feature_extraction:
    - resnet50

weights_dir: ./pretrained_weights
hf_key: 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
