site_name: PathBench v2
theme:
name: material
nav:
- Home: index.md
- Design Principles: design-principles.md
- Extending: extending.md
- API:
- Datasets: api/datasets.md
- Models: api/models.md
- Tasks: api/tasks.md
- Losses: api/losses.md